### ISSUE TITLE
Potential typo

### ISSUE THREAD

**Issue by Guyonsteroids** [TUM-Dev/TUMenu#118]
In [line 50 of Sidebar.tsx](https://github.com/TUM-Dev/TUMenu/blob/fb9fd87c0e9b9be8aa9ef3f4930ca99c58a07ea8/components/Sidebar/Sidebar.tsx#L50), is this supposed to be “Planegg” instead of “Plategg”?

**Comment by CommanderStorm** [comment]
Good catch!

Would you like to create a PR (having this contribution linked to your account) or should I/another person commit the change?

**Comment by Guyonsteroids** [comment]
I've made a [PR](https://github.com/TUM-Dev/TUMenu/pull/119)
