### ISSUE TITLE
[Feature Request] Add Menu support for TUM Heilbronn

### ISSUE THREAD

**Issue by Guyonsteroids** [TUM-Dev/TUMenu#120]
Since the eat-api now [supports TUM Heilbronn](https://github.com/TUM-Dev/eat-api/commit/43aee84ceeeedfb17f10128acd19cfdbb0c7379c), would it be possible to add support for it?

From my brief glance at the code I think it would just require another elif condition [here](https://github.com/TUM-Dev/TUMenu/blob/fb9fd87c0e9b9be8aa9ef3f4930ca99c58a07ea8/components/Sidebar/Sidebar.tsx#L59) to check for the value Heilbronn right? It may be that I might be missing something i.e. adding the location to the map.

**Comment by marinovl7** [comment]
Hi, first of all thank you for pointing that out! Yes exactly we will need to add another city object like the others [here](https://github.com/TUM-Dev/TUMenu/blob/fb9fd87c0e9b9be8aa9ef3f4930ca99c58a07ea8/components/Sidebar/Sidebar.tsx#L37) and add additional elif confition as you said and that's it! 

Would you also like to submit a PR for this feature?

**Comment by Guyonsteroids** [comment]
Awesome, I'd love to work on it.

**Comment by marinovl7** [comment]
Great! Looking forward to your PR!

**Comment by Guyonsteroids** [comment]
Good evening, sorry for the delay, but I've made the PR. Please do note that I have not tested the changes.
